export { makeStyles, useTheme, withTheme } from '@material-ui/core/styles'
export { BaseCSSProperties } from '@material-ui/core/styles/withStyles'
export { Theme } from '@material-ui/core/styles/createMuiTheme'
export { default as color } from './color'
export { setTheme } from './color'
